const mongoose = require('mongoose');

const teacherSchema = new mongoose.Schema({
    name: { type: String },
    gender: { type: String },
    phone: { type: String },
    telegram: { type: String },
    alternativePhone: { type: String },
    photo: { type: String },
    whatsapp: { type: String },
    email: { type: String },
    facebookLink: { type: String },
    familyPhone: { type: String },
    friendPhone: { type: String },
    city: { type: String },
    division: { type: String },
    district: { type: String },
    thana: { type: String },
    currentArea: { type: String },
    expectedTuitionAreas: { type: String },
    fullAddress: { type: String },
    university: { type: String },
    department: { type: String },
    academicYear: { type: String },
    medium: { type: String },
    mastersDept: { type: String },
    mastersUniversity: { type: String },
    honorsDept: { type: String },
    honorsUniversity: { type: String },
    hscGroup: { type: String },
    hscResult: { type: String },
    college: { type: String },
    sscGroup: { type: String },
    school: { type: String },
    sscResult: { type: String },
    experience: { type: String },
    favoriteSubject: { type: String },
    premiumCode: { type: String },
    uniCode: { type: String },
    password: { type: String },
    status: { type: String },
    transactionId: { type: String },
    rating: { type: Number },
    review: { type: String },
    paymentType: { type: String },
    amount: { type: String },
    commentFromTeacher: { type: String },
    comment: { type: String },
    isBiodataShow: { type: Boolean, default: false },
    isResultShow: { type: Boolean, default: false },
    createdAt: { type: Date, default: Date.now }
});

const RegTeacher = mongoose.model('RegTeacher', teacherSchema);
module.exports = RegTeacher;
