const mongoose = require('mongoose');

const tuitionSchema = new mongoose.Schema({
    tuitionCode: { type: String, required: true, unique: true, index: true },
    isPublish: { type: Boolean, default: true },
    wantedTeacher: String,
    student: String,
    institute: String,
    class: String,
    medium: String,
    subject: String,
    time: String,
    day: String,
    salary: String,
    location: String,
    area: String,
    guardianNumber: String,
    city: String,
    guardian_source_medium: { type: String, default: '' },
    status: String,
    note: String,
    guardianDemandForPublic: { type: String, default: '' },
    taskAssignedTo: String,
    tutorNumber: String,
    createdBy: String,
    updatedBy: String,
    lastAvailableCheck: { type: Date },
    lastUpdate: { type: Date },
    lastUpdateComment: { type: String },
    nextUpdateDate: { type: Date },
    nextUpdateComment: { type: String },
    comment1: { type: String },
    comment2: { type: String },
    tuitionCancelReason: { type: String },
    tuitionCancelReasonPublic: { type: String },
    guardianBehavior: { type: String },
    isWhatsappApply: { type: Boolean, default: false },
    joining: { type: String, default: '' },
    isUrgent: { type: Boolean, default: false },
    isPaymentCreated: { type: Boolean, default: false },
    assignedTo: { type: String, default: '' },
    previousAssignedTo: { type: String, default: '' },
    isSpamGuardian: { type: Boolean, default: false },
    isBestGuardian: { type: Boolean, default: false },
    isReviewDone: { type: Boolean, default: false },
    agentComment: { type: String },
    isSoftDelete: { type: Boolean, default: false },
    mediaFee: { type: String, default: '60%' },
    lastPublishedDate: { type: Date },
}, {
    timestamps: true
});
const Tuition = mongoose.model('Tuition', tuitionSchema);
module.exports = Tuition;
